name: DiscordWhitelister
version: 1.5.0
api-version: 1.17
author: Braden Holmes
main: uk.co.angrybee.joe.DiscordWhitelister
description: Discord Whitelister.
softdepend: [PlaceholderAPI]
commands:
  discord:
    description: Get the link to the Discord
    usage: /<command>